using FluentValidation;

namespace WebApiWithEndpointMapper.Endpoints;
// This class implements the IMapEndpoint interface from the Svrooij.EndpointMapper package (this file is also generated by the source generator)
public class FluentValidationEndpoint : Svrooij.EndpointMapper.IMapEndpoint
{
    public static void MapEndpoint(IEndpointRouteBuilder app)
    {
        // Define your endpoint(s) here.
        // I would recommend using just a single endpoint per class for clarity
        app
          .MapPost("/users", PostNewUserAsync)
          .WithOpenApi()
          .WithTags("Users")
          .AddValidationWithUserDtoValidator();
    }

    private static async Task<IResult> PostNewUserAsync(UserDto userDto)
    {
        // Here you would have your logic to handle the new user
        return Results.Ok($"User {userDto.Name} with email {userDto.Email} created successfully!");
    }
}

/// <summary>
/// Validator for UserDto.
/// The validation filter and extension method are auto-generated by the source generator.
/// Just define your validator by implementing AbstractValidator&lt;T&gt;, and the filter will be automatically generated.
/// Then use .AddValidationWithUserDtoValidator() on your route handler builder to apply the validation.
/// </summary>
internal class UserDtoValidator : AbstractValidator<UserDto>
{
    public UserDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty().WithMessage("Name is required.")
            .MinimumLength(2);
        RuleFor(x => x.Email)
            .NotEmpty().WithMessage("Email is required.")
            .EmailAddress().WithMessage("A valid email is required.");
    }
}