
namespace WebApiWithEndpointMapper.Endpoints;
// This class implements the IMapEndpoint interface from the Svrooij.EndpointMapper package (this file is also generated by the source generator)
public class MyFirstEndpoint : Svrooij.EndpointMapper.IMapEndpoint
{
    public static void MapEndpoint(IEndpointRouteBuilder app)
    {
        // Define your endpoint(s) here.
        // I would recommend using just a single endpoint per class for clarity
        app
          .MapGet("/myfirstendpoint", () => "Hello from MyFirstEndpoint!")
          .WithOpenApi();
    }
}