using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Svrooij.EndpointMapper.Generators;

[Generator]
public class FluentValidationSchemaTransformerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var schemas = context.SyntaxProvider
                   .CreateSyntaxProvider(
       predicate: (node, _) => node is ClassDeclarationSyntax cls &&
       cls.AttributeLists.SelectMany(al => al.Attributes).Any(a => a.Name.ToString().Contains("GenerateSchema")),
              transform: (ctx, _) => ExtractSchemaInfo(ctx))
             .Where(x => x.validatorSymbol != null);

        context.RegisterSourceOutput(
       context.CompilationProvider.Combine(schemas.Collect()),
       (spc, source) =>
    {
        var (comp, items) = source;
        if (items.IsEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.AspNetCore.OpenApi;");
        sb.AppendLine("using Microsoft.OpenApi.Models;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = items[0].ns;
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public class FluentValidationSchemaTransformer : IOpenApiSchemaTransformer");
        sb.AppendLine("{");
        sb.AppendLine("    public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)");
        sb.AppendLine("    {");

        foreach (var item in items)
        {
            var rules = ExtractRules(item.validatorSymbol, comp);
            sb.AppendLine("        string? key = null;");
            sb.AppendLine($"        if (context.JsonTypeInfo.Type == typeof({item.dtoName}))");
            sb.AppendLine("        {");
            sb.AppendLine("            key = null;");

            foreach (var rule in rules)
            {
                var (prop, minLen, maxLen, isEmail, isRequired) = rule;
                sb.AppendLine();
                sb.AppendLine($"            key = schema.Properties.Keys.FirstOrDefault(k => k.Equals(\"{prop}\", StringComparison.OrdinalIgnoreCase));");
                sb.AppendLine($"            if (key != null)");
                sb.AppendLine("            {");

                if (minLen > 0)
                    sb.AppendLine($"              schema.Properties[key].MinLength = {minLen};");
                if (maxLen > 0)
                    sb.AppendLine($"              schema.Properties[key].MaxLength = {maxLen};");
                if (isEmail)
                    sb.AppendLine($"              schema.Properties[key].Format = \"email\";");
                if (isRequired)
                {
                    sb.AppendLine($"              schema.Properties[key].Nullable = false;");
                    sb.AppendLine($"              schema.Required.Add(key);");
                }

                sb.AppendLine("            }");

            }

            sb.AppendLine("        }");
        }

        sb.AppendLine("        return Task.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("FluentValidationSchemaTransformer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    });
    }

    private static (string dtoName, string ns, INamedTypeSymbol validatorSymbol) ExtractSchemaInfo(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        var sym = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
        if (sym == null) return default;

        var attr = sym.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "GenerateSchemaAttribute");
        if (attr?.ConstructorArguments.Length != 1) return default;

        var validatorType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
        if (validatorType == null) return default;

        return (sym.ToDisplayString(), sym.ContainingNamespace.ToDisplayString(), validatorType);
    }

    private static List<(string prop, int minLen, int maxLen, bool isEmail, bool isRequired)> ExtractRules(INamedTypeSymbol validatorSym, Compilation comp)
    {
        var rules = new List<(string, int, int, bool, bool)>();

        // Try to get the source tree from the validator symbol
        var location = validatorSym.Locations.FirstOrDefault();
        if (location?.SourceTree == null)
            return rules;

        var root = location.SourceTree.GetRoot();
        if (root == null) return rules;

        // Find the actual class declaration of the validator
        var validatorClassName = validatorSym.Name;
        var validatorDeclaration = root.DescendantNodes()
                 .OfType<ClassDeclarationSyntax>()
                 .FirstOrDefault(cls => cls.Identifier.ValueText == validatorClassName);

        if (validatorDeclaration == null)
            return rules;

        // Get the constructor
        var constructors = validatorDeclaration.Members
        .OfType<ConstructorDeclarationSyntax>();

        foreach (var ctor in constructors)
        {
            // Find all RuleFor calls within the constructor
            var ruleForCalls = ctor.DescendantNodes()
             .OfType<InvocationExpressionSyntax>()
         .Where(inv =>
                {
                    var expr = inv.Expression.ToString();
                    return expr.Contains("RuleFor");
                });

            foreach (var call in ruleForCalls)
            {
                if (call.ArgumentList.Arguments.Count == 0) continue;

                var lambdaArg = call.ArgumentList.Arguments[0];
                if (!(lambdaArg.Expression is LambdaExpressionSyntax lambda)) continue;

                string? propName = null;
                if (lambda.Body is MemberAccessExpressionSyntax member)
                    propName = member.Name.Identifier.ValueText;

                if (string.IsNullOrEmpty(propName)) continue;

                var (minLen, maxLen, isEmail, isRequired) = AnalyzeValidationChain(call);
                rules.Add((propName!, minLen, maxLen, isEmail, isRequired));
            }
        }

        return rules;
    }

    private static (int minLen, int maxLen, bool isEmail, bool isRequired) AnalyzeValidationChain(InvocationExpressionSyntax ruleForCall)
    {
        int minLen = 0, maxLen = 0;
        bool isEmail = false, isRequired = false;

        // RuleFor(...) is the innermost call. The chain .NotEmpty().WithMessage().MinimumLength(2)...
        // wraps it as parent InvocationExpressionSyntax nodes in the AST.
        // We walk UP through the parents to find all chained validation calls.
        var node = ruleForCall.Parent;

        while (node != null)
        {
            // Each chained call like .NotEmpty() appears as:
            //   InvocationExpressionSyntax
            //     MemberAccessExpressionSyntax  <-- holds the method name
            //       <previous invocation>       <-- the receiver
            //     ArgumentListSyntax            <-- the arguments (e.g. the length value)
            if (node is InvocationExpressionSyntax invocation &&
                invocation.Expression is MemberAccessExpressionSyntax memberAccess)
            {
                var methodName = memberAccess.Name.Identifier.ValueText;

                if (methodName == "NotEmpty")
                {
                    isRequired = true;
                }
                else if (methodName == "MinimumLength" || methodName == "MinLength")
                {
                    if (invocation.ArgumentList.Arguments.Count > 0 &&
                        invocation.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax minLit &&
                        int.TryParse(minLit.Token.ValueText, out int minVal))
                        minLen = minVal;
                }
                else if (methodName == "MaximumLength" || methodName == "MaxLength")
                {
                    if (invocation.ArgumentList.Arguments.Count > 0 &&
                        invocation.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax maxLit &&
                        int.TryParse(maxLit.Token.ValueText, out int maxVal))
                        maxLen = maxVal;
                }
                else if (methodName == "Length")
                {
                    // Length(min, max) sets both bounds; Length(exact) sets both to the same value
                    if (invocation.ArgumentList.Arguments.Count == 2 &&
                        invocation.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lenMinLit &&
                        invocation.ArgumentList.Arguments[1].Expression is LiteralExpressionSyntax lenMaxLit &&
                        int.TryParse(lenMinLit.Token.ValueText, out int lenMin) &&
                        int.TryParse(lenMaxLit.Token.ValueText, out int lenMax))
                    {
                        minLen = lenMin;
                        maxLen = lenMax;
                    }
                    else if (invocation.ArgumentList.Arguments.Count == 1 &&
                        invocation.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax exactLit &&
                        int.TryParse(exactLit.Token.ValueText, out int exactLen))
                    {
                        minLen = exactLen;
                        maxLen = exactLen;
                    }
                }
                else if (methodName == "EmailAddress")
                {
                    isEmail = true;
                }
            }

            // Stop climbing once we leave the fluent chain into a statement or block
            if (node is StatementSyntax)
                break;

            node = node.Parent;
        }

        return (minLen, maxLen, isEmail, isRequired);
    }
}
