using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Svrooij.EndpointMapper.Generators;

namespace Svrooij.EndpointMapper;

/// <summary>
/// Generates SelectDto extension methods for DTOs marked with the [GenerateSelect] attribute.
/// </summary>
[Generator]
public sealed class SelectDtoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var selectDtoDeclarations = context.SyntaxProvider
 .CreateSyntaxProvider(
    predicate: static (s, _) => IsSyntaxTarget(s),
transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var compilationAndSelectDtos = context.CompilationProvider.Combine(selectDtoDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndSelectDtos, static (spc, source) =>
      {
          var (compilation, selectDtos) = source;
          GenerateSelectDtoExtensions(compilation, selectDtos!, spc);
      });
    }

    private static bool IsSyntaxTarget(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDeclaration || classDeclaration.AttributeLists.Count == 0)
            return false;

        // Check if any attribute starts with "GenerateSelect" at syntax level
        return classDeclaration.AttributeLists.Any(attrList =>
         attrList.Attributes.Any(attr =>
    {
        var attrName = attr.Name.ToString();
        return attrName == "GenerateSelect" ||
 attrName == "GenerateSelectAttribute" ||
   attrName.EndsWith(".GenerateSelect") ||
attrName.EndsWith(".GenerateSelectAttribute");
    }));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (classSymbol == null)
            return null;

        // Check if the class has the GenerateSelect attribute
        var hasGenerateSelectAttribute = classSymbol.GetAttributes().Any(attr =>
            attr.AttributeClass?.Name == "GenerateSelectAttribute" &&
     attr.AttributeClass?.ContainingNamespace.ToDisplayString() == "Svrooij.EndpointMapper");

        return hasGenerateSelectAttribute ? classSymbol : null;
    }

    private static void GenerateSelectDtoExtensions(Compilation compilation, ImmutableArray<INamedTypeSymbol> selectDtoClasses, SourceProductionContext context)
    {
        if (selectDtoClasses.IsEmpty)
            return;

        var sourceBuilder = new System.Text.StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine("using System.Linq;");
        sourceBuilder.AppendLine();

        // Group extensions by namespace
        var groupedByNamespace = selectDtoClasses
               .GroupBy(c => c.ContainingNamespace.ToDisplayString())
                 .ToList();

        foreach (var namespaceGroup in groupedByNamespace)
        {
            var namespaceName = namespaceGroup.Key;
            sourceBuilder.AppendLine($"namespace {namespaceName}");
            sourceBuilder.AppendLine("{");

            foreach (var dtoClass in namespaceGroup)
            {
                // Get the GenerateSelect attribute
                var generateSelectAttribute = dtoClass.GetAttributes()
          .FirstOrDefault(attr =>
              attr.AttributeClass?.Name == "GenerateSelectAttribute" &&
                         attr.AttributeClass?.ContainingNamespace.ToDisplayString() == "Svrooij.EndpointMapper");

                if (generateSelectAttribute == null)
                    continue;

                // Extract the entity type from the attribute constructor argument
                if (generateSelectAttribute.ConstructorArguments.Length != 1)
                    continue;

                var entityTypeArg = generateSelectAttribute.ConstructorArguments[0];
                if (entityTypeArg.Value is not INamedTypeSymbol entityType)
                    continue;

                var dtoClassName = dtoClass.Name;
                var dtoFullName = dtoClass.ToDisplayString();
                var entityFullName = entityType.ToDisplayString();

                // Generate the extension method
                SelectDtoTextHelper.GenerateSelectDtoExtensionMethod(sourceBuilder, dtoClassName, dtoFullName, entityFullName, dtoClass, entityType);
            }
            sourceBuilder.AppendLine("}");
        }

        context.AddSource("SelectDtoExtensions.g.cs", SourceText.From(sourceBuilder.ToString(), System.Text.Encoding.UTF8));
    }
}
