using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using Svrooij.EndpointMapper.Generators;

namespace Svrooij.EndpointMapper;

/// <summary>
/// Generates validation filters and extension methods for classes implementing AbstractValidator&lt;T&gt;.
/// </summary>
[Generator]
public sealed class ValidatorFilterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validatorDeclarations = context.SyntaxProvider
          .CreateSyntaxProvider(
   predicate: static (s, _) => IsSyntaxTarget(s),
            transform: static (ctx, _) => GetSemanticTarget(ctx))
     .Where(static m => m is not null);

        var compilationAndValidators = context.CompilationProvider.Combine(validatorDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndValidators, static (spc, source) =>
        {
            var (compilation, validators) = source;
            GenerateValidationFilters(compilation, validators.Cast<(INamedTypeSymbol, INamedTypeSymbol?)>().ToImmutableArray(), spc);
        });
    }

    private static bool IsSyntaxTarget(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDeclaration || classDeclaration.BaseList == null)
            return false;

        // Check if any base type contains "AbstractValidator" at syntax level
        return classDeclaration.BaseList.Types.Any(baseType =>
          baseType.Type.ToString().Contains("AbstractValidator"));
    }

    private static (INamedTypeSymbol, INamedTypeSymbol?)? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (classSymbol == null)
            return null;

        // Find the AbstractValidator<T> base type or IValidator<T> interface
        var abstractValidatorBase = classSymbol.AllInterfaces.FirstOrDefault(i =>
       i.Name == "IValidator" &&
           i.ContainingNamespace.ToDisplayString() == "FluentValidation" &&
       i.TypeArguments.Length == 1);

        if (abstractValidatorBase == null)
        {
            // Try to find it in the base classes directly
            var baseTypes = classSymbol.BaseType;
            while (baseTypes != null)
            {
                if (baseTypes.Name == "AbstractValidator" &&
             baseTypes.ContainingNamespace.ToDisplayString() == "FluentValidation" &&
              baseTypes.TypeArguments.Length == 1)
                {
                    var dtoType = baseTypes.TypeArguments[0] as INamedTypeSymbol;
                    return (classSymbol, dtoType);
                }
                baseTypes = baseTypes.BaseType;
            }
            return null;
        }

        // Extract the DTO type from IValidator<T>
        var dtoType2 = abstractValidatorBase.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
        return (classSymbol, dtoType2);
    }

    private static void GenerateValidationFilters(Compilation compilation, ImmutableArray<(INamedTypeSymbol ValidatorClass, INamedTypeSymbol? DtoType)> validators, SourceProductionContext context)
    {
        if (validators.IsEmpty)
            return;

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated />");
        sourceBuilder.AppendLine("using Microsoft.AspNetCore.Builder;");
        sourceBuilder.AppendLine("using Microsoft.AspNetCore.Http;");
        sourceBuilder.AppendLine("using FluentValidation;");
        sourceBuilder.AppendLine("using System.Linq;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("#nullable enable");

        // Group validators by namespace
        var groupedByNamespace = validators
  .Where(v => v.DtoType != null)
      .GroupBy(v => v.ValidatorClass.ContainingNamespace.ToDisplayString())
   .ToList();

        foreach (var namespaceGroup in groupedByNamespace)
        {
            var namespaceName = namespaceGroup.Key;
            sourceBuilder.AppendLine($"namespace {namespaceName}");
            sourceBuilder.AppendLine("{");

            foreach (var (validatorClass, dtoType) in namespaceGroup)
            {
                if (dtoType == null)
                    continue;

                var validatorClassName = validatorClass.Name;
                var validatorFullName = validatorClass.ToDisplayString();
                var dtoClassName = dtoType.Name;
                var dtoFullName = dtoType.ToDisplayString();

                // Generate the validation filter class
                ValidatorTextHelper.GenerateValidationFilter(
                   sourceBuilder,
                 validatorClassName,
                  validatorFullName,
                   dtoClassName,
               dtoFullName);
            }

            sourceBuilder.AppendLine("}");
        }

        context.AddSource("ValidationExtensions.g.cs", SourceText.From(sourceBuilder.ToString(), System.Text.Encoding.UTF8));
    }
}
